# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D3dH1gUrABCFWEMwn5LeDs5_ZHHGmWiV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('sample_owid_covid_data.csv')

print(df)

print(df.isnull().sum())

df['Tcountry'] = df.groupby('iso_code')['total_cases'].transform('sum')

df['date'] = pd.to_datetime(df['date'])
df = df.sort_values(['iso_code','date'])
df['daily_vaccinations'] = df.groupby('iso_code')['total_vaccinations'].diff()
df['Trends'] = (df.groupby('iso_code')['daily_vaccinations'].rolling(window=5,min_periods=1).mean().reset_index(level=0,drop=True))
print(df['Trends'])

df_sorted  = df.sort_values('date')
plt.plot (df_sorted['date'],df_sorted['total_cases'])
plt.title("Cases Over Time")
plt.xlabel("Cases")
plt.ylabel("Date")
plt.xticks(rotation=45)

top = df.groupby('iso_code')['total_deaths'].sum().sort_values(ascending=False).head(10)
plt.bar(top.index,top.values)
plt.title('Top 10 countries by death toll')
plt.xlabel('Countries')
plt.ylabel('Deaths')

loc = df.groupby('location')['total_vaccinations'].max().sort_values(ascending=False).head(10)
plt.pie(loc.values, labels=loc.index, autopct='%1.1f%%', startangle=140)
plt.title('Vaccination Distribution (Top 10 Countries)')
plt.tight_layout()
plt.show()

